# Generated by Django 5.2.3 on 2025-06-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
